obj-$(CONFIG_ARCH_DAVINCI_DA8XX) += da8xx-cfgchip.o
obj-$(CONFIG_ARCH_DAVINCI_DA8XX) += da8xx-usb-phy-clk.o
obj-y += pll.o

obj-$(CONFIG_ARCH_DAVINCI_DA830)	+= psc-da830.o
obj-$(CONFIG_ARCH_DAVINCI_DA850)	+= psc-da850.o
obj-$(CONFIG_ARCH_DAVINCI_DM355)	+= psc-dm355.o
obj-$(CONFIG_ARCH_DAVINCI_DM365)	+= psc-dm365.o
obj-$(CONFIG_ARCH_DAVINCI_DM644x)	+= psc-dm644x.o
obj-$(CONFIG_ARCH_DAVINCI_DM646x)	+= psc-dm646x.o
obj-y					+= psc.o
